#!/bin/sh
cd "${0%/*}" || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Clean the case
cleanCase

# Remove any additional files if needed
rm -rf constant/extendedFeatureEdgeMesh
rm -f constant/triSurface/*.eMesh

# ----------------------------------------------------------------- end-of-file